
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_LANCE_HNS 2
#define PARTNER_SILVER_MEGANIUM_HNS 3
#define PARTNER_SILVER_TYPHLOSION_HNS 4
#define PARTNER_SILVER_FERALIGATR_HNS 5
#define PARTNER_DUMMY 6
#define PARTNER_COUNT 7
//Tests need PARTNER_COUNT to be at least 3 so we add a dummy partner

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
