BattleFrontier_Lounge4_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook_hns::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns:
	.string "I wonder if they'll be airing interviews\n"
	.string "with tough TRAINERS today?$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns:
	.string "If I opened a restaurant here,\n"
	.string "it'd make money for sure.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns:
	.string "Whew…\p"
	.string "I need to take a breather after\n"
	.string "some intense battles…\p"
	.string "But even now, I never take a break\n"
	.string "from plotting strategy and combos.$"

